
events {}

http {
    map $http_upgrade $connection_upgrade {
            default upgrade;
            '' close;
        }
    server{
        listen 80;
        server_name kamaldinovnt.ru;

        location / {
            return 301 https://$host$request_uri;
        }
        location /.well-known/acme-challenge/ {
            root /var/www/certbot;
        }
    }

    server {

        listen 443 ssl;
        server_name kamaldinovnt.ru;

        ssl_certificate /etc/letsencrypt/live/kamaldinovnt.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/kamaldinovnt.ru/privkey.pem;

        location / {
            proxy_pass http://web_fastapi:8000;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }





    }

    server {

        listen 443 ssl;
        server_name s3.kamaldinovnt.ru;

        ssl_certificate /etc/letsencrypt/live/s3.kamaldinovnt.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/s3.kamaldinovnt.ru/privkey.pem;

        location / {
            proxy_pass http://web_minio:9000;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
        }

    server {

        listen 443 ssl;
        server_name console.s3.kamaldinovnt.ru;

        ssl_certificate /etc/letsencrypt/live/console.s3.kamaldinovnt.ru/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/console.s3.kamaldinovnt.ru/privkey.pem;

        location / {
            proxy_pass http://web_minio:9001;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /ws/ {
            proxy_pass http://web_minio:9001;
            proxy_http_version 1.1;

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;

            proxy_buffering off;
            proxy_read_timeout 3600s;
            proxy_send_timeout 3600s;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}

